services:
  user-service:
    build:
      context: .
      dockerfile: ./Server/Dockerfile
    hostname: user-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 127.0.0.1:5000:80
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10
        window: 60s
